spring:
  redis:
    host: ${REDIS_CACHE_HOSTNAME}
    port: 6380
    password: ${REDIS_CACHE_PRIMARY_KEY}
    ssl: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
  cloud:
    azure:
      servicebus:
        namespace: ${SERVICEBUS_NAMESPACE}
        entity-name: ${SERVICEBUS_QUEUE_NAME}
        entity-type: queue
      active-directory:
        b2c:
          enabled: true
          base-uri: ${AUTHORIZATION_SERVER_BASE_URI}
          profile:
            tenant-id: 9c393d8a-42f8-4fce-8ca9-44a852917008
          credential:
            client-id: 412c97ee-be7b-46bc-b707-8c8ec98e1bdc
          user-flows:
            sign-up-or-sign-in: ${SIGN_UP_OR_SIGN_IN_FLOW_NAME}
server:
  port: 8082