spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://fs19eventmanagement.b2clogin.com/9c393d8a-42f8-4fce-8ca9-44a852917008/v2.0/
          audience: https://fs19eventmanagement.onmicrosoft.com/412c97ee-be7b-46bc-b707-8c8ec98e1bdc
          jwk-set-uri: https://login.microsoftonline.com/5a3e7946-7ac8-45cd-82c5-1527818e7dff/discovery/v2.0/keys
  redis:
    host: ${REDIS_CACHE_HOSTNAME}
    port: 6380
    password: ${REDIS_CACHE_PRIMARY_KEY}
    ssl: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://login.microsoftonline.com/5a3e7946-7ac8-45cd-82c5-1527818e7dff/v2.0
#          audience: api://fc037e21-c170-48d2-9aa8-543878aff8b1
#          jwk-set-uri: https://login.microsoftonline.com/5a3e7946-7ac8-45cd-82c5-1527818e7dff/discovery/v2.0/keys
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update #create-drop
  cloud:
    azure:
      servicebus:
        namespace: ${SERVICEBUS_NAMESPACE}
        entity-name: ${SERVICEBUS_QUEUE_NAME}
        entity-type: queue
